### ISSUE TITLE
Permit specifying alternative Myria instances

### ISSUE THREAD

**Issue by kadamwhite** [vega/vega-lite-ui#121]
This issue had to be punted from #77, which has some back story:

from @domoritz :
> Myria is a distributed database systems I've worked on and we wanted to show how polestar/voyager could integrate with other tools. Read more about myria at http://myria.cs.
>
> The demo instance is the only instance that is publicly available. One issue with it is that it doesn't support ssl at this point.

**Comment by dundalek** [comment]
Hi, thanks for improving the dataset loading. As for specifying alternative Myria instace, I think a simple input field would do, which would allow to change the default URL.

As for a real world usage: I created a simple [adapter to visualize info about OS](https://github.com/dundalek/osquery-rest-adapter) using Voyager. It works by providing Myria-compatible HTTP interface. Now I have to manually edit source code to change the `myriaRest` constant to localhost. It would be nice just to change it using the UI.

**Comment by domoritz** [comment]
@dundalek I love your osquery rest adapter! I haven't seen it before. Fantastic idea. I think @kanitw and I should provide a simpler mechanism to add your own plugin so that you can adapt the UI a bit.

As for this feature, I actually added an input field to change the myria rest url in #149. We just haven't deployed yet because there are some pending vega and vega-lite changes that break the current master (but will make it better ;-)).
