### ISSUE TITLE
Period in CSV field names causes an error

### ISSUE THREAD

**Issue by kadamwhite** [vega/vega-lite-ui#133]
This sample content
```csv
DATE,Appt. Time,# Stops,Wait
4/22/14,9:00 AM,6,16
```
causes an error when the CSV is added to Voyager: Vega Lite cannot parse the `Appt. Title` field name due to the period, despite this being a technically-valid field

**Comment by domoritz** [comment]
That sounds like a datalib issue. Can you flag it there?

**Comment by jheer** [comment]
__NOT__ a datalib issue (but maybe a Vega issue). Observe:
```
// In console at http://vega.github.io/datalib/:
var txt = 'DATE,Appt. Time,# Stops,Wait\n4/22/14,9:00 AM,6,16';
JSON.stringify(dl.read(txt, {type: 'csv'}));
> [{"DATE": "4/22/14","Appt. Time":"9:00 AM","# Stops":"6","Wait": "16"}]
```

**Comment by jheer** [comment]
My guess is that the problem is not the initial parsing, but downstream. In particular, I suspect an accessor function is being constructed for that field name, and the `.` is being parsed a field separator. If so, one workaround would be to escape any dots used within field names: `"Appt\\. Time"`.

**Comment by domoritz** [comment]
Okay. We generally haven't tested `.` and ` ` in variable names. There is a vega lite issue for that in https://github.com/vega/vega-lite/issues/358. I bumped up its priority.
