### ISSUE TITLE
Redesign Function List for TimeUnit 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite-ui#210]

**Comment by ZeningQu** [comment]
Option 1
- [ ] Tableau Style timeUnit with examples

![screen shot 2016-08-12 at 2 18 31 pm](https://cloud.githubusercontent.com/assets/822034/17637306/b4e84dd0-6097-11e6-8add-ddc6e4773341.png)


Option 2
- [ ] Add dash to longer timeUnits: `YEAR-MONTH-DATE`, `YEAR-MONTH-DATE-HOURS-MINUTES-SECONDS`
- [ ] Make corresponding changes in Vega-Lite, so that the function name in axis title is consistent with the function name in the function list
