### ISSUE TITLE
AngularJS dependency

### ISSUE THREAD

**Issue by hy9be** [vega/vega-lite-ui#292]
Hi, I am wondering if you guys have any specific reasons to have the whole UI package built on top of AngularJS. AngularJS is a very opinionated framework and thus the usage for the framework will be limited in the AngularJS ecosystem.

**Comment by kanitw** [comment]
Hi,  Thanks for the asking. 

The reason is simply that we began building this before React became cool and widely adopted and before Angular team announced that they will deprecate AngularJS v1.    

If we were to start building this now, we won't use AngularJS v1.  That said, we also do not have resources to implement it with other framework (at least for now).
